task_manager/labels/urls.py
from django.urls import path

from . import views

app_name = "labels"

urlpatterns = [
    path("", views.LabelListView.as_view(), name="labels_list"),
    path("create/", views.LabelCreateView.as_view(), name="labels_create"),
    path(
        "<int:pk>/update/",
        views.LabelUpdateView.as_view(),
        name="labels_update",
    ),
    path(
        "<int:pk>/delete/",
        views.LabelDeleteView.as_view(),
        name="labels_delete",
    ),
]

task_manager/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.TaskListView.as_view(), name="tasks_list"),
    path("create/", views.TaskCreateView.as_view(), name="tasks_create"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="tasks_detail"),
    path(
        "<int:pk>/update/", views.TaskUpdateView.as_view(), name="tasks_update"
    ),
    path(
        "<int:pk>/delete/", views.TaskDeleteView.as_view(), name="tasks_delete"
    ),
]

task_manager/urls.py
# task_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from task_manager.views import index
from task_manager.users.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path(
        "users/",
        include(("task_manager.users.urls", "users"), namespace="users"),
    ),
    path(
        "tasks/",
        include(("task_manager.tasks.urls", "tasks"), namespace="tasks"),
    ),
    path(
        "statuses/",
        include(
            ("task_manager.statuses.urls", "statuses"), namespace="statuses"
        ),
    ),
    path(
        "labels/",
        include(("task_manager.labels.urls", "labels"), namespace="labels"),
    ),
]

task_manager/users/urls.py
# task_manager/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.UserListView.as_view(), name="users_list"),
    path("create/", views.UserCreateView.as_view(), name="users_create"),
    path(
        "<int:pk>/update/", views.UserUpdateView.as_view(), name="users_update"
    ),
    path(
        "<int:pk>/delete/", views.UserDeleteView.as_view(), name="users_delete"
    ),
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name=_("Name"))
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
        verbose_name=_("Name"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Creation date"),
    )

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.contrib.auth.models import User
from django.db import models

from task_manager.labels.models import Label
from task_manager.statuses.models import Status


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="tasks_authored"
    )
    executor = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="tasks_executed",
    )
    status = models.ForeignKey(
        Status, on_delete=models.PROTECT, related_name="tasks"
    )
    labels = models.ManyToManyField(Label, blank=True, related_name="tasks")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

task_manager/users/models.py
# В этом приложении используется встроенная модель User,
# поэтому дополнительной пользовательской модели не определено.

task_manager/labels/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ["name"]
        labels = {
            "name": _("Label name"),
        }

task_manager/statuses/forms.py
from django import forms

from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ["name"]

task_manager/tasks/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from .models import Task


class TaskForm(forms.ModelForm):
    executor = forms.ModelChoiceField(
        queryset=User.objects.all(),
        label=_("Executor"),
        required=False,
        empty_label=_("---------"),
        to_field_name="id",
    )

    class Meta:
        model = Task
        fields = ["name", "description", "status", "executor", "labels"]
        labels = {
            "name": _("Name"),
            "description": _("Description"),
            "status": _("Status"),
            "executor": _("Executor"),
            "labels": _("Labels"),
        }
        widgets = {
            "description": forms.Textarea(attrs={"rows": 3}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["executor"].label_from_instance = (
            lambda obj: f"{obj.first_name} {obj.last_name}"
        )

task_manager/labels/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import LabelForm
from .models import Label


class LabelListView(LoginRequiredMixin, ListView):
    model = Label
    template_name = "labels/list.html"
    context_object_name = "labels"


class LabelCreateView(LoginRequiredMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = "labels/create.html"
    success_url = reverse_lazy("labels:labels_list")

    def form_valid(self, form):
        messages.success(self.request, _("Label was successfully created"))
        return super().form_valid(form)


class LabelUpdateView(LoginRequiredMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = "labels/update.html"
    success_url = reverse_lazy("labels:labels_list")

    def form_valid(self, form):
        messages.success(self.request, _("Label was successfully updated"))
        return super().form_valid(form)


class LabelDeleteView(LoginRequiredMixin, DeleteView):
    model = Label
    template_name = "labels/delete.html"
    success_url = reverse_lazy("labels:labels_list")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.tasks.exists():
            messages.error(
                request,
                _("Cannot delete the label because it is in use"),
            )
            return redirect(self.success_url)

        self.object.delete()
        messages.success(request, _("Label was successfully deleted"))
        return redirect(self.success_url)

task_manager/statuses/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import StatusForm
from .models import Status


class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = "statuses/list.html"
    context_object_name = "statuses"


class StatusCreateView(LoginRequiredMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = "statuses/create.html"
    success_url = reverse_lazy("statuses:statuses_list")

    def form_valid(self, form):
        messages.success(self.request, _("Status was successfully created"))
        return super().form_valid(form)


class StatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = "statuses/update.html"
    success_url = reverse_lazy("statuses:statuses_list")

    def form_valid(self, form):
        messages.success(self.request, _("Status was successfully updated"))
        return super().form_valid(form)


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = "statuses/delete.html"
    success_url = reverse_lazy("statuses:statuses_list")
    context_object_name = "status"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.tasks.exists():
            messages.error(
                request,
                _("Cannot delete the status because it is in use"),
            )
            return redirect(self.success_url)

        messages.success(request, _("Status was successfully deleted"))
        return super().post(request, *args, **kwargs)

task_manager/tasks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from .forms import TaskForm
from .models import Task


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"
    context_object_name = "tasks"

    def get_queryset(self):
        queryset = Task.objects.all()

        status_id = self.request.GET.get("status")
        executor_id = self.request.GET.get("executor")
        label_id = self.request.GET.get("label")
        only_self = self.request.GET.get("only_my_tasks")

        if status_id:
            queryset = queryset.filter(status_id=status_id)
        if executor_id:
            queryset = queryset.filter(executor_id=executor_id)
        if label_id:
            queryset = queryset.filter(labels__id=label_id)
        if only_self:
            queryset = queryset.filter(author=self.request.user)

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["statuses"] = Status.objects.all()
        context["executors"] = User.objects.all()
        context["labels"] = Label.objects.all()
        context["filter_params"] = self.request.GET
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/detail.html"
    context_object_name = "task"


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/create.html"
    success_url = reverse_lazy("tasks:tasks_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, _("Task was successfully created"))
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/update.html"
    success_url = reverse_lazy("tasks:tasks_list")

    def form_valid(self, form):
        messages.success(self.request, _("Task was successfully updated"))
        return super().form_valid(form)


class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy("tasks:tasks_list")

    def test_func(self):
        return self.request.user == self.get_object().author

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request, _("You are not authenticated! Please log in.")
            )
            return redirect("login")
        messages.error(self.request, _("Only the author can delete a task."))
        return redirect("tasks:tasks_list")

    def post(self, request, *args, **kwargs):
        messages.success(self.request, _("Task was successfully deleted"))
        return super().post(request, *args, **kwargs)

task_manager/users/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import UserForm, UserChangeForm


class UserListView(ListView):
    model = User
    template_name = "users/list.html"
    context_object_name = "users"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(
            "DEBUG: Messages in UserListView:",
            list(messages.get_messages(self.request)),
        )
        return context


class UserCreateView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = "users/create.html"
    success_url = reverse_lazy("login")
    success_message = _("User was successfully registered")


class UserUpdateView(
    SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView
):
    model = User
    form_class = UserChangeForm
    template_name = "users/update.html"
    success_url = reverse_lazy("users:users_list")
    success_message = _("User was successfully updated")

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        return self.request.user == self.get_object()

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request, _("You are not authenticated! Please log in.")
            )
            return redirect("login")
        messages.error(
            self.request, _("You don't have permission to edit another user.")
        )
        return redirect("users:users_list")


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    template_name = "users/delete.html"
    success_url = reverse_lazy("users:users_list")

    def test_func(self):
        return self.request.user == self.get_object()

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request, _("You are not authenticated! Please log in.")
            )
            return redirect("login")
        messages.error(
            self.request, _("You don't have permission to delete another user.")
        )
        return redirect("users:users_list")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        messages.success(self.request, _("User was successfully deleted"))
        return super().post(request, *args, **kwargs)


class CustomLoginView(LoginView):
    def form_valid(self, form):
        messages.success(self.request, _("You are logged in"))
        return super().form_valid(form)


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.info(self.request, _("You are logged out"))
        return super().dispatch(request, *args, **kwargs)

task_manager/views.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView


def index(request):
    return render(request, "index.html")


class UserListView(ListView):
    model = User
    template_name = "users/list.html"
    context_object_name = "users"


class UserCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "users/create.html"
    success_url = reverse_lazy("login")


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = "users/update.html"
    success_url = reverse_lazy("users:list")

    def test_func(self):
        return self.request.user.pk == self.get_object().pk


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    template_name = "users/delete.html"
    success_url = reverse_lazy("users:list")

    def test_func(self):
        return self.request.user.pk == self.get_object().pk

task_manager/templates/tasks/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block title %}{% trans "Create task" %}{% endblock %}

{% block content %}
<div class="container mt-4">
  <h1 class="my-4">{% trans "Create task" %}</h1>

  <form method="post">
    {% csrf_token %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    <div class="mb-3">
      <label for="{{ form.name.id_for_label }}" class="form-label">{% trans "Name" %}</label>
      {{ form.name }}
      {% if form.name.errors %}
        <div class="invalid-feedback d-block">
          {% for error in form.name.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="{{ form.description.id_for_label }}" class="form-label">{% trans "Description" %}</label>
      {{ form.description }}
      {% if form.description.errors %}
        <div class="invalid-feedback d-block">
          {% for error in form.description.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="{{ form.status.id_for_label }}" class="form-label">{% trans "Status" %}</label>
      {{ form.status }}
      {% if form.status.errors %}
        <div class="invalid-feedback d-block">
          {% for error in form.status.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="{{ form.executor.id_for_label }}" class="form-label">{% trans "Executor" %}</label>
      {{ form.executor }}
      {% if form.executor.errors %}
        <div class="invalid-feedback d-block">
          {% for error in form.executor.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="{{ form.labels.id_for_label }}" class="form-label">{% trans "Labels" %}</label>
      {{ form.labels }}
      {% if form.labels.errors %}
        <div class="invalid-feedback d-block">
          {% for error in form.labels.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
      <br>
      <small class="form-text text-muted">{% trans "Hold Ctrl to select multiple labels" %}</small>
    </div>

    <button type="submit" class="btn btn-primary">{% trans "Create" %}</button>
  </form>
</div>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Delete task" %}{% endblock %}
{% block content %}
  <h1>{% trans "Task deletion" %}</h1>
  <p>{% blocktrans with task_name=object.name %}Are you sure you want to delete task "{{ task_name }}"?{% endblocktrans %}</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
    <a href="{% url 'tasks:tasks_list' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
  </form>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Task details" %}{% endblock %}

{% block content %}
  <h1>{% trans "Task details" %}</h1>

  <h3>{{ task.name }}</h3>

  {% if task.description %}
    <p><strong>{% trans "Description:" %}</strong> {{ task.description }}</p>
  {% endif %}

  {% if task.author %}
    <p><strong>{% trans "Author:" %}</strong> {{ task.author.get_full_name }}</p>
  {% endif %}

  {% if task.executor %}
    <p><strong>{% trans "Executor:" %}</strong> {{ task.executor.get_full_name }}</p>
  {% endif %}

  {% if task.status %}
    <p><strong>{% trans "Status:" %}</strong> {{ task.status.name }}</p>
  {% endif %}

  {% if task.labels.exists %}
    <p><strong>{% trans "Labels:" %}</strong>
      {% for label in task.labels.all %}
        {{ label.name }}{% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
  {% endif %}

  <a href="{% url 'tasks:tasks_update' task.pk %}" class="btn btn-warning">
    {% trans "Edit" %}
  </a>
  <a href="{% url 'tasks:tasks_delete' task.pk %}" class="btn btn-danger">
    {% trans "Delete" %}
  </a>
  <a href="{% url 'tasks:tasks_list' %}" class="btn btn-secondary">
    {% trans "Back" %}
  </a>
{% endblock %}

task_manager/templates/tasks/list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Tasks" %}{% endblock %}

{% block content %}
  <h1>{% trans "Tasks" %}</h1>

  <a href="{% url 'tasks:tasks_create' %}" class="btn btn-primary mb-3">
    {% trans "Create task" %}
  </a>

  <form method="get" class="mb-4">
    <div class="mb-2">
      <label for="id_status">{% trans "Status" %}</label>
      <select name="status" id="id_status" class="form-select">
        <option value="">{% trans "---------" %}</option>
        {% for status in statuses %}
          <option value="{{ status.id }}" {% if request.GET.status == status.id|stringformat:"s" %}selected{% endif %}>{{ status.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="mb-2">
      <label for="id_executor">{% trans "Executor" %}</label>
      <select name="executor" id="id_executor" class="form-select">
        <option value="">{% trans "---------" %}</option>
        {% for user in executors %}
          <option value="{{ user.id }}" {% if request.GET.executor == user.id|stringformat:"s" %}selected{% endif %}>{{ user.get_full_name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="mb-2">
      <label for="id_label">{% trans "Label" %}</label>
      <select name="label" id="id_label" class="form-select">
        <option value="">{% trans "---------" %}</option>
        {% for label in labels %}
          <option value="{{ label.id }}" {% if request.GET.label == label.id|stringformat:"s" %}selected{% endif %}>{{ label.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-check mb-2">
      <input type="checkbox" name="only_my_tasks" id="id_only_my_tasks" class="form-check-input"
             {% if request.GET.only_my_tasks %}checked{% endif %}>
      <label class="form-check-label" for="id_only_my_tasks">
        {% trans "Only my tasks" %}
      </label>
    </div>
    <button type="submit" class="btn btn-outline-primary">{% trans "Show" %}</button>
  </form>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans "ID" %}</th>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Status" %}</th>
        <th>{% trans "Author" %}</th>
        <th>{% trans "Executor" %}</th>
        <th>{% trans "Creation date" %}</th>
        <th>{% trans "Actions" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
      <tr>
        <td>{{ task.id }}</td>
        <td><a href="{% url 'tasks:tasks_detail' task.pk %}">{{ task.name }}</a></td>
        <td>{{ task.status }}</td>
        <td>{{ task.author.get_full_name }}</td>
        <td>{{ task.executor.get_full_name }}</td>
        <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
        <td>
          <a href="{% url 'tasks:tasks_update' task.pk %}">{% trans "Update" %}</a><br>
          <a href="{% url 'tasks:tasks_delete' task.pk %}">{% trans "Delete" %}</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="7">{% trans "No tasks" %}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 i18n %}
{% block title %}{% trans "Edit task" %}{% endblock %}
{% block content %}
  <h1>{% trans "Edit task" %}</h1>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label">{% trans "Name" %}</label>
      {{ form.name }}
    </div>
    <div class="mb-3">
      <label for="id_description" class="form-label">{% trans "Description" %}</label>
      {{ form.description }}
    </div>
    <div class="mb-3">
      <label for="id_status" class="form-label">{% trans "Status" %}</label>
      {{ form.status }}
    </div>
    <div class="mb-3">
      <label for="id_executor" class="form-label">{% trans "Executor" %}</label>
      {{ form.executor }}
    </div>
    <div class="mb-3">
      <label for="id_labels" class="form-label">{% trans "Labels" %}</label>
      {{ form.labels }}
    </div>
    <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
  </form>
{% endblock %}